export const recipeData = [
    {
        id: 1,
        name:"Steak and Cheese Wraps",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Shaved Steak", "Cheese", "Wrap", "Various Colored Peppers", "Onion"],
        lastCooked: "",
    },
    {
        id: 2,
        name:"Breakfast for Dinner",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Eggs", "Diced Potatoes", "Sausage", "Bacon"],
        lastCooked: "",
    },
    {
        id: 3,
        name:"Scrambled Eggs",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Eggs", "Salt", "Pepper", "Milk"],
        lastCooked: "",
    },
    {
        id: 4,
        name:"Quesadillas",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Chicken", "Various Colored Bell Peppers", "Shredded Cheese", "Onions", "Tortillas"],
        lastCooked: "",
    },
    {
        id: 5,
        name:"Homemade Chicken Tenders",
        category: "",
        cookInstructions: ["", ""],
        description: "",
        ingredients: ["Chicken", "Panko", "Eggs"],
        lastCooked: "",
    },
    {
        id: 6,
        name:"Lemon Chicken Orzo",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Chicken", "Lemons", "Orzo Pasta"],

    },
    {
        id: 7,
        name:"Steak and Cheese Stuffed Peppers",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Shaved Steak", "Various Colored Bell Peppers", "Cheese"],
        lastCooked: "",
    },
    {
        id: 8,
        name:"Mini Build Your Own Pizza",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Pizza Sauce", "Shredded Cheese"],
        lastCooked: "",
    },
    {
        id: 9,
        name:"Meatloaf",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "Ketchup", "Eggs"],
        lastCooked: "",
    },
    {
        id: 10,
        name:"BBQ Meatloaf",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "BBQ Sauce", "Eggs"],
        lastCooked: "",
    },
    {
        id: 11,
        name:"Grilled Cheese",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Bread", "Sliced Cheese"],
        lastCooked: "",
    },
    {
        id: 12,
        name:"Buffalo Chicken Grilled Cheese",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Sliced Bread", "Sliced Cheese", "Chicken", "Buffalo Sauce", "Eggs", "Panko"],
        lastCooked: "",
    },
    {
        id: 13,
        name:"Buffalo Chicken Dip",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Chicken", "Buffalo Sauce"],
        lastCooked: "",
    },
    {
        id: 14,
        name:"Shepard's Pie",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "Mashed Potatoes", "Corn"],
        lastCooked: "",
    },
    {
        id: 15,
        name:"Tacos",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "Hard or Soft Taco Shells", "Shredded Cheese", "Shredded Lettuce"],
        lastCooked: "",
    },
    {
        id: 16,
        name:"Enchiladas",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Enchilada Sauce", "Chicken", "Shredded Cheese", "Tortillas"],
        lastCooked: "",
    },
    {
        id: 17,
        name:"Pasta and Meatballs",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Pasta", "Meatballs", "Pasta Sauce"],
        lastCooked: "",
    },
    {
        id: 18,
        name:"Nachos",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Nacho Chips", "Shredded Cheese"],
        lastCooked: "",
    },
    {
        id: 19,
        name:"Burger",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "Burger Buns", "Sliced Cheese"],
        lastCooked: "",
    },
    {
        id: 20,
        name:"Chili",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "Kidney Beans", "Tomato Paste", "Tomato Sauce", "Onions", "Bell Pepper", "Shredded Cheese", "Sour Cream", "Corn Bread"],
        lastCooked: "",
    },
    {
        id: 21,
        name:"Lasagna",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Oven Ready Lasagna Noodles", "Sauce", "Mozzarella Cheese", "Ricotta Cheese", "Hamburger", "Sausage"],
        lastCooked: "",
    },
    {
        id: 22,
        name:"Pulled BBQ Chicken Sandwiches",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Chicken", "BBQ Sauce", "Burger Buns", "Cheese"],
        lastCooked: "",
    },
    {
        id: 23,
        name:"Mini Burger Sliders",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "Mini Burger Buns", "Sliced Cheese"],
        lastCooked: "",
    },
    {
        id: 24,
        name:"Chicken and Veggie Stir-Fry",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Chicken", "Broccoli"],
        lastCooked: "",
    },
    {
        id: 25,
        name:"Chicken Broccoli Alfredo",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Boneless, Skinless Chicken Breats", "Broccoli", "Heavy Cream", "Nutmeg", "Salt", "Pepper", "Grated Parmesan Cheese", "Butter", "Minced Garlic", "Penne Pasta"],
        lastCooked: "",
    },
    {
        id: 26,
        name:"Mac and Cheese",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Macaroni Pasta", "Cheese"],
        lastCooked: "",
    },
    {
        id: 27,
        name:"Buffalo Mac and Cheese",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Macaroni Pasta", "Cheese", "Buffalo Sauce"],
        lastCooked: "",
    },
    {
        id: 28,
        name:"Chicken Tender Wraps",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Chicken", "Shredded Cheese", "Wraps"],
        lastCooked: "",
    },
    {
        id: 29,
        name:"Hot Dogs and Beans",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hot Dogs", "Hot Dog Buns", "Baked Beans"],
        lastCooked: "",
    },
    {
        id: 30,
        name:"Pork Chops",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Pork Chops", "Eggs", "Panko"],
        lastCooked: "",
    },
    {
        id: 31,
        name:"Bagels",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Bagels", "Cream Cheese"],
        lastCooked: "",
    },
    {
        id: 32,
        name:"Mozzarella Sticks",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Low-moisture Mozzarella Cheese", "Flour", "Sea Salt", "Pepper", "Garlic Powder", "Eggs", "Panko", "Italian Seasoning"],
        lastCooked: "",
    },
    {
        id: 33,
        name:"Broccoli",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Broccoli"],
        lastCooked: "",
    },
    {
        id: 34,
        name:"Diced Sweet Potatoes",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Sweet Potatoes"],
        lastCooked: "",
    },
    {
        id: 35,
        name:"Baked Sweet Potato",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Sweet Potato"],
        lastCooked: "",
    },
    {
        id: 36,
        name:"Baked Potato",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Potato"],
        lastCooked: "",
    },
    {
        id: 37,
        name:"French Toast",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Bread", "Eggs", "Cinnamon"],
        lastCooked: "",
    },
    {
        id: 38,
        name:"Steamed White Rice",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["White Rice"],
        lastCooked: "",
    },
    {
        id: 39,
        name:"Waffles",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Eggs", "Flour", "White Sugar", "Milk", "Baking Powder", "Salt", "Vanilla Extract", "Butter"],
        lastCooked: "",
    },
    {
        id: 40,
        name:"Risotto",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Arborio Rice", "Chicken Stock", "Vegetable Oil", "Butter", "Medium Shallot", "Dry White Wine", "Parmesan Cheese", "Italian Parsley", "Kosher Salt", "Black Pepper"],
        lastCooked: "",
    },
    {
        id: 41,
        name:"Haddock",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Haddock", "Crackers", "Butter", "Lemon", "Milk"],
        lastCooked: "",
    },
    {
        id: 42,
        name:"Cod",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Cod", "Crackers", "Butter", "Lemon", "Milk"],
        lastCooked: "",
    },
    {
        id: 43,
        name:"Creamy Sausage Tortellini",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hot Italian Sausage", "Chicken Broth", "Canned Diced Tomatoes", "Heavy Whipping Cream", "Cheese Tortellini", "Spinach"],
        lastCooked: "",
    },
    {
        id: 44,
        name:"Buffalo Veggie Patties",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Buffalo Veggie Patties", "Sandwich Thins"],
        lastCooked: "",
    },
    {
        id: 45,
        name:"Fire Roasted Carrots",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Fire Roasted Carrots"],
        lastCooked: "",
    },
    {
        id: 46,
        name:"Buffalo Cauliflower Wings",
        category: "",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Buffalo Sauce", "Cauliflower", "Panko"],
        lastCooked: "",
    },
]