//Data Item Template Next id 49
/*{
    id: 1,
    name:"",
    category: "",
    cookInstructions: ["", ""],
    cookTemp: "",   
    description: "",
    ingredients: ["", "", "", "", ""],
    lastCooked: "",
},*/

export const recipeData = [
    {
        id: 1,
        name:"Steak and Cheese Wraps",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Shaved Steak", "Cheese", "Wrap", "Various Colored Peppers", "Onion"],
        lastCooked: "",
    },
    {
        id: 2,
        name:"Breakfast for Dinner",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Eggs", "Diced Potatoes", "Sausage", "Bacon"],
        lastCooked: "",
    },
    {
        id: 3,
        name:"Scrambled Eggs",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Eggs", "Salt", "Pepper", "Milk"],
        lastCooked: "",
    },
    {
        id: 4,
        name:"Quesadillas",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Chicken", "Various Colored Bell Peppers", "Shredded Cheese", "Onions", "Tortillas"],
        lastCooked: "",
    },
    {
        id: 5,
        name:"Homemade Chicken Tenders",
        category: "Main",
        cookInstructions: ["", ""],
        description: "",
        ingredients: ["Chicken", "Panko", "Eggs"],
        lastCooked: "",
    },
    {
        id: 6,
        name:"Lemon Chicken Orzo",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Chicken", "Lemons", "Orzo Pasta"],
        lastCooked: "",
    },
    {
        id: 7,
        name:"Steak and Cheese Stuffed Peppers",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Shaved Steak", "Various Colored Bell Peppers", "Cheese"],
        lastCooked: "",
    },
    {
        id: 8,
        name:"Mini Build Your Own Pizza",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Pizza Sauce", "Shredded Cheese"],
        lastCooked: "",
    },
    {
        id: 9,
        name:"Meatloaf",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "Ketchup", "Eggs"],
        lastCooked: "",
    },
    {
        id: 10,
        name:"BBQ Meatloaf",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "BBQ Sauce", "Eggs"],
        lastCooked: "",
    },
    {
        id: 11,
        name:"Grilled Cheese",
        category: "Main",
        cookInstructions: ["Butter the outsides of the bread slices.", "Put the buttered side face down.", "Put sliced cheese and top of sandwhich with the buttered side face up on the other slide that is buttered side face down.", "Once that faced down side it toasted, flip it to the other buttered side.", "Once cheese is melted, take it off heat, wait for it to cool, then enjoy."],
        cookTemp: "",   
        description: "",
        ingredients: ["Bread", "Sliced Cheese"],
        lastCooked: "1/15",
    },
    {
        id: 12,
        name:"Buffalo Chicken Grilled Cheese",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Sliced Bread", "Sliced Cheese", "Chicken", "Buffalo Sauce", "Eggs", "Panko"],
        lastCooked: "",
    },
    {
        id: 13,
        name:"Buffalo Chicken Dip",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Chicken", "Buffalo Sauce"],
        lastCooked: "",
    },
    {
        id: 14,
        name:"Shepard's Pie",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "Mashed Potatoes", "Corn"],
        lastCooked: "",
    },
    {
        id: 15,
        name:"Tacos",
        category: "Main",
        cookInstructions: ["Cook meat until it changes colors usually a white color for chicken.", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "Hard or Soft Taco Shells", "Shredded Cheese", "Shredded Lettuce"],
        lastCooked: "",
    },
    {
        id: 16,
        name:"Enchiladas",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Enchilada Sauce", "Chicken", "Shredded Cheese", "Tortillas"],
        lastCooked: "",
    },
    {
        id: 17,
        name:"Pasta and Meatballs",
        category: "Main",
        cookInstructions: ["Cook pasta for 12 minutes.", "Cook meatballs until thawed."],
        cookTemp: "",   
        description: "",
        ingredients: ["Pasta", "Meatballs", "Pasta Sauce"],
        lastCooked: "1/17",
    },
    {
        id: 18,
        name:"Nachos",
        category: "Main",
        cookInstructions: ["Put chees on chips and microwave until desired meltiness.", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Nacho Chips", "Shredded Cheese"],
        lastCooked: "",
    },
    {
        id: 19,
        name:"Burger",
        category: "Main",
        cookInstructions: ["Take burger meat and separate it into desired size.", "Cook on grill until cooked to your preference.", "Put on hamburger buns with cheese or whatever other toppings that are desired."],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "Burger Buns", "Sliced Cheese"],
        lastCooked: "",
    },
    {
        id: 20,
        name:"Chili",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "Kidney Beans", "Tomato Paste", "Tomato Sauce", "Onions", "Bell Pepper", "Shredded Cheese", "Sour Cream", "Corn Bread"],
        lastCooked: "",
    },
    {
        id: 21,
        name:"Lasagna",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Oven Ready Lasagna Noodles", "Sauce", "Mozzarella Cheese", "Ricotta Cheese", "Hamburger", "Sausage"],
        lastCooked: "",
    },
    {
        id: 22,
        name:"Pulled BBQ Chicken Sandwiches",
        category: "Main",
        cookInstructions: ["Cook the chicken in the crock pot.", "Shred it with two forks separating them."],
        cookTemp: "",   
        description: "",
        ingredients: ["Chicken", "BBQ Sauce", "Burger Buns", "Cheese"],
        lastCooked: "",
    },
    {
        id: 23,
        name:"Mini Burger Sliders",
        category: "Main",
        cookInstructions: ["Take burger meat and separate it into desired size.", "Cook on grill until cooked to your preference.", "Put on hamburger buns with cheese or whatever other toppings that are desired."],
        cookTemp: "",   
        description: "",
        ingredients: ["Hamburger", "Mini Burger Buns", "Sliced Cheese"],
        lastCooked: "",
    },
    {
        id: 24,
        name:"Chicken and Veggie Stir-Fry",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Chicken", "Broccoli"],
        lastCooked: "",
    },
    {
        id: 25,
        name:"Chicken Broccoli Alfredo",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Boneless, Skinless Chicken Breats", "Broccoli", "Heavy Cream", "Nutmeg", "Salt", "Pepper", "Grated Parmesan Cheese", "Butter", "Minced Garlic", "Penne Pasta"],
        lastCooked: "",
    },
    {
        id: 26,
        name:"Mac and Cheese",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Macaroni Pasta", "Cheese"],
        lastCooked: "",
    },
    {
        id: 27,
        name:"Buffalo Mac and Cheese",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Macaroni Pasta", "Cheese", "Buffalo Sauce"],
        lastCooked: "",
    },
    {
        id: 28,
        name:"Chicken Tender Wraps",
        category: "Main",
        cookInstructions: ["Heat wraps up to make it easier to wrap.", "Cook chicken per instructions on the bag."],
        cookTemp: "",   
        description: "",
        ingredients: ["Chicken", "Shredded Cheese", "Wraps"],
        lastCooked: "",
    },
    {
        id: 29,
        name:"Hot Dogs and Beans",
        category: "Main and Side",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hot Dogs", "Hot Dog Buns", "Baked Beans"],
        lastCooked: "",
    },
    {
        id: 30,
        name:"Pork Chops",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Pork Chops", "Eggs", "Panko"],
        lastCooked: "",
    },
    {
        id: 31,
        name:"Bagels",
        category: "Main",
        cookInstructions: ["Cook in toaster for desired amount of toasting.", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Bagels", "Cream Cheese"],
        lastCooked: "",
    },
    {
        id: 32,
        name:"Mozzarella Sticks",
        category: "Side",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Low-moisture Mozzarella Cheese", "Flour", "Sea Salt", "Pepper", "Garlic Powder", "Eggs", "Panko", "Italian Seasoning"],
        lastCooked: "",
    },
    {
        id: 33,
        name:"Broccoli",
        category: "Side",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Broccoli"],
        lastCooked: "",
    },
    {
        id: 34,
        name:"Diced Sweet Potatoes",
        category: "Side",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Sweet Potatoes"],
        lastCooked: "",
    },
    {
        id: 35,
        name:"Baked Sweet Potato",
        category: "Side",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Sweet Potato"],
        lastCooked: "",
    },
    {
        id: 36,
        name:"Baked Potato",
        category: "Side",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Potato"],
        lastCooked: "",
    },
    {
        id: 37,
        name:"French Toast",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Bread", "Eggs", "Cinnamon"],
        lastCooked: "",
    },
    {
        id: 38,
        name:"Steamed White Rice",
        category: "Side",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["White Rice"],
        lastCooked: "",
    },
    {
        id: 39,
        name:"Waffles",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Eggs", "Flour", "White Sugar", "Milk", "Baking Powder", "Salt", "Vanilla Extract", "Butter"],
        lastCooked: "",
    },
    {
        id: 40,
        name:"Risotto",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Arborio Rice", "Chicken Stock", "Vegetable Oil", "Butter", "Medium Shallot", "Dry White Wine", "Parmesan Cheese", "Italian Parsley", "Kosher Salt", "Black Pepper"],
        lastCooked: "",
    },
    {
        id: 41,
        name:"Haddock",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Haddock", "Crackers", "Butter", "Lemon", "Milk"],
        lastCooked: "",
    },
    {
        id: 42,
        name:"Cod",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Cod", "Crackers", "Butter", "Lemon", "Milk"],
        lastCooked: "",
    },
    {
        id: 43,
        name:"Creamy Sausage Tortellini",
        category: "Main",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Hot Italian Sausage", "Chicken Broth", "Canned Diced Tomatoes", "Heavy Whipping Cream", "Cheese Tortellini", "Spinach"],
        lastCooked: "",
    },
    {
        id: 44,
        name:"Buffalo Veggie Patties",
        category: "Main",
        cookInstructions: ["Cook for 15 minutes.", ""],
        cookTemp: "425",   
        description: "",
        ingredients: ["Buffalo Veggie Patties", "Sandwich Thins", "Sliced Cheese"],
        lastCooked: "",
    },
    {
        id: 45,
        name:"Fire Roasted Carrots",
        category: "Side",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "",
        ingredients: ["Fire Roasted Carrots"],
        lastCooked: "",
    },
    {
        id: 46,
        name:"Buffalo Cauliflower Wings",
        category: "Side",
        cookInstructions: ["Cook for 20 minutes if bagged version.", ""],
        cookTemp: "425 if bagged version.",   
        description: "",
        ingredients: ["Buffalo Sauce", "Cauliflower", "Panko"],
        lastCooked: "",
    },
    {
        id: 47,
        name:"Broccoli Cheddar Soup",
        category: "Side",
        cookInstructions: ["", ""],
        cookTemp: "",   
        description: "Usually a Panera premade.",
        ingredients: ["", "", ""],
        lastCooked: "",
    },
    {
        id: 48,
        name:"Pork Loin",
        category: "Main",
        cookInstructions: ["Glass pan", "Put a layer of tin foil", "Put pork loin in and close tin foil around it", "Leave in oven for 30 minutes"],
        cookTemp: "400",   
        description: "",
        ingredients: ["Pork Loin usually pre-marinaded",],
        lastCooked: "",
    },
]